import time
import json
import httpx
from pydantic import BaseModel, ValidationError
from config import OLLAMA_URL, MAX_RETRIES, DEFAULT_TEMPERATURE


class AgentResult(BaseModel):
    success: bool
    data: dict | None = None
    error: str | None = None
    retry_count: int = 0
    ttft_ms: float | None = None
    tokens_per_sec: float | None = None
    total_ms: float | None = None
    cold_start: bool = False


class BaseAgent:
    # subclasses must define these
    system_prompt: str = ""
    schema: type[BaseModel] = None

    def __init__(self, model: str):
        self.model = model

    def run(self, user_input: str, cold_start: bool = False) -> AgentResult:
        prompt = user_input
        retry_count = 0
        validation_error_msg = None

        while retry_count <= MAX_RETRIES:
            # append validation error from previous attempt if any
            if validation_error_msg:
                prompt = (
                    f"{user_input}\n\n"
                    f"Your previous attempt failed validation:\n"
                    f"{validation_error_msg}\n"
                    f"Try again."
                )

            raw, ttft_ms, tokens_per_sec, total_ms = self._call_ollama(prompt)

            if raw is None:
                return AgentResult(
                    success=False,
                    error="Ollama call failed — no response received",
                    retry_count=retry_count,
                    cold_start=cold_start,
                )

            parsed, validation_error_msg = self._validate(raw)

            if parsed is not None:
                return AgentResult(
                    success=True,
                    data=parsed.model_dump(),
                    retry_count=retry_count,
                    ttft_ms=ttft_ms,
                    tokens_per_sec=tokens_per_sec,
                    total_ms=total_ms,
                    cold_start=cold_start,
                )

            retry_count += 1

        return AgentResult(
            success=False,
            error=f"Schema validation failed after {MAX_RETRIES} retries. Last error: {validation_error_msg}",
            retry_count=MAX_RETRIES,
            ttft_ms=ttft_ms,
            tokens_per_sec=tokens_per_sec,
            total_ms=total_ms,
            cold_start=cold_start,
        )

    def _call_ollama(
        self, user_input: str
    ) -> tuple[str | None, float | None, float | None, float | None]:
        """
        Send a chat request to Ollama.
        Returns (raw_content, ttft_ms, tokens_per_sec, total_ms).
        Uses streaming to capture time-to-first-token accurately.
        """
        payload = {
            "model": self.model,
            "messages": [
                {"role": "system", "content": self.system_prompt},
                {"role": "user", "content": user_input},
            ],
            "format": "json",
            "options": {"temperature": DEFAULT_TEMPERATURE},
            "stream": True,
        }

        ttft_ms = None
        total_content = []
        token_count = 0
        start = time.perf_counter()

        try:
            with httpx.stream(
                "POST",
                f"{OLLAMA_URL}/api/chat",
                json=payload,
                timeout=120.0,
            ) as response:
                response.raise_for_status()
                for line in response.iter_lines():
                    if not line:
                        continue
                    chunk = json.loads(line)
                    content = chunk.get("message", {}).get("content", "")
                    if content:
                        if ttft_ms is None:
                            ttft_ms = (time.perf_counter() - start) * 1000
                        total_content.append(content)
                    if chunk.get("done"):
                        # eval_count is the actual number of tokens generated by Ollama
                        token_count = chunk.get("eval_count", 0)
                        break

        except Exception as e:
            print(f"[base_agent] Ollama call failed: {type(e).__name__}: {e}")
            return None, None, None, None

        total_ms = (time.perf_counter() - start) * 1000
        raw = "".join(total_content)

        # tokens_per_sec based on generation time after first token
        generation_ms = total_ms - (ttft_ms or 0)
        tokens_per_sec = (
            round(token_count / (generation_ms / 1000), 2)
            if generation_ms > 0
            else None
        )

        return raw, round(ttft_ms, 2) if ttft_ms else None, tokens_per_sec, round(total_ms, 2)

    def _validate(self, raw: str) -> tuple[BaseModel | None, str | None]:
        """
        Parse raw JSON string and validate against the agent's schema.
        Returns (parsed_model, error_message).
        """
        try:
            data = json.loads(raw)
        except json.JSONDecodeError as e:
            return None, f"Response was not valid JSON: {e}"

        if not isinstance(data, dict):
            return None, f"Expected a JSON object, got {type(data).__name__}"

        try:
            parsed = self.schema(**data)
            return parsed, None
        except ValidationError as e:
            # format errors cleanly for the retry prompt
            errors = []
            for err in e.errors():
                field = ".".join(str(x) for x in err["loc"])
                errors.append(f"  - {field}: {err['msg']}")
            return None, "\n".join(errors)
